# Leo
基于standard2.0跨平台类库的各种尝试。以官方类库为主，整合了以下功能。
<ol>
    <li>
        <p4>DI依赖注入</p4>
        <ul>
            <li>Microsoft.Extensions.DependencyInjection</li>
            <li><a>https://github.com/autofac/Autofac</a>Autofac</li>
        </ul>
    </li>
    <li>
        <p4>Logging日志</p4>
        <ul>
            <li>Sqlite</li>
            <li>Console</li>
        </ul>
    </li>
    <li>
        <p4>Repository仓储模式</p4>
        <ul>
            <li>Dapper</li>
            <li>EF</li>
            <li>AutoMapper</li>
        </ul>
    </li>
    <li><p4>Caching缓存</p4></li>
</ol>
